const PONCTUATION = [".", "!", "?"];
const SEPARATORS = [",", ":", ";"];

const quote_strict_classic_mapping = [
    ["don't", "do not"],
    ["doesn't", "does not"],
    ["hasn't", "has not"],
    ["haven't", "have not"],
    ["i've", "i have"],
    ["we've", "we have"],
    ["you've", "you have"],
    ["they've", "they have"],
    ["can't", "cannot"],
    ["couldn't", "could not"],
    ["mustn't", "must not"],
    ["'ll", " will"],
    ["won't", " will not"],
    ["weren't", "were not"],
    ["let's", " let us"],
    ["wouldn't", " would not"],
    ["hadn't", "had not"],
    ["who's", "who is"],
    ["they're", "they are"],
    ["we're", "we are"],
    ["i'm", "i am"],
    ["you're", "you are"],
    ["shouldn't", "should not"],
    ["wasn't", "was not"],
    ["aren't", "are not"],
    ["isn't", "is not"],
    ["didn't", "did not"],
    ["what's", "what is"],
    ["shan't", "shall not"],
]

const american_contractions = [
    ["gonna", "going to"],
    ["wanna", "want to"],
    ["gotta", "have got to"],
    ["gona", "going to"],
    ["wana", "want to"],
    ["gota", "have got to"],
]

const not_quoted_classic_contractions = [
    ["dont", "do not"],
    ["doesnt", "does not"],
    ["hasnt", "has not"],
    ["havent", "have not"],
    ["ive", "i have"],
    ["youve", "you have"],
    ["weve", "we have"],
    ["theyve", "they have"],
    ["cant", "cannot"],
    ["couldnt", "could not"],
    ["mustnt", "must not"],
    ["shant", "shall not"],
    ["wont", " will not"],
    ["hadnt", "had not"],
    ["werent", "were not"],
    ["whats", "what is"],
    ["whos", "who is"],
    ["im", "i am"],
    ["theyre", "they are"],
    ["theyre", "they are"],
    ["shouldnt", "should not"],
    ["youre", "you are"],
    ["isnt", "is not"],
    ["wasnt", "was not"],
    ["didnt", "did not"],
    ["arent", "are not"],
]